trigger:
- dev

stages:
- stage: BuildWebAPI
  jobs:
  - job: BuildWebAPI
    pool: Default
    steps:
    - powershell: dotnet publish 'PokeAPI/PokeAPI.csproj' -c Release -o artifact
    - powershell: Compress-Archive artifact/* '$(Build.ArtifactStagingDirectory)/PokeAPI.zip'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'PokeAPIDrop'
        publishLocation: 'Container'