trigger:
- none
resources:
  pipelines:
  - pipeline: DeployPokeDbUpdateApp # Name of the pipeline resource.
    source: BuildPokeDbUpdateApp # The name of the pipeline referenced by this pipeline resource.
    trigger: none

stages:
- stage: DeployDev
  jobs:
  - job:
    pool: Default
    steps:
    - template: deploy-functionapp-template.yml  # Template reference
      parameters:
        env: 'dev'
- stage:
  jobs:
  - deployment: DeployProd
    environment: 'yaml-deploy'
    pool: Default
    strategy:
      runOnce:
        deploy:
          steps:
          - template: deploy-functionapp-template.yml  # Template reference
            parameters:
              env: prod
          