trigger:
- none

stages:
- stage: BuildReact
  jobs:
  - job: BuildReact
    steps:
    - powershell: npm install
      workingDirectory: '$(Build.SourcesDirectory)/pokesearchapp'
    - powershell: npm run build
      workingDirectory: '$(Build.SourcesDirectory)/pokesearchapp'

    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)/pokesearchapp/build'
        contents: '**/*' 
        targetFolder: $(Build.ArtifactStagingDirectory)
      displayName: 'Copy npm package'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/npm.zip
        replaceExistingArchive: true
   
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/npm.zip'
        artifactName: npm
